name: juan_giphy
description: "An application for viewing GIFs on the Giphy platform."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  rename: ^3.0.2
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/app_icon.png
    - assets/images/giphy.png
    - assets/images/giphy_developers.gif
